<?php
if(!isset($model->sTitle)){
    $model = json_decode($model);
    $model->sTitle = $model->data[0]->title;
}
layout("layout.phtml");
$model = $model->data[0];
?>

<!-- Title -->
<h1 itemprop="title"><?php echo $model->title ?></h1>

<!-- Author -->
<p class="lead">
    by <span itemprop="hiringOrganization" itemscope itemtype="http://schema.org/Organization"><span itemprop="name"><?php echo $model->hiringOrganizationName ?></span></span>
</p>

<hr>

<!-- Date/Time -->
<p><span class="glyphicon glyphicon-time"></span> Posted on <span itemprop="datePosted"><?php echo $model->datePosted ?></span></p>

<hr>

<!-- Preview Image In this spot we would put a map-->
            <div style="overflow:hidden;height:300px;width:100%;">
                <script src="https://maps.google.com/maps/api/js"></script>
                <script>
                    var latitude = <?php echo $model->jobLocationLatitude ?>;
                    var longitude = <?php echo $model->jobLocationLongitude ?>;
                    google.maps.event.addDomListener(window, "load", function(){
                        var myOptions = {
                            zoom: 14,
                            center: new google.maps.LatLng(latitude, longitude),
                            mapTypeId: google.maps.MapTypeId.ROADMAP,
                            scrollwheel: false
                        };
                        map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                        marker = new google.maps.Marker({
                            map: map,
                            position: new google.maps.LatLng(latitude, longitude)
                        });
                        infowindow = new google.maps.InfoWindow({
                            content: "<b><?php echo $model->hiringOrganizationName ?></b><br/><?php echo $model->hiringOrganizationAddress ?>"
                        });
                        google.maps.event.addListener(marker, "click", function () {
                            infowindow.open(map, marker);
                        });
                        infowindow.open(map, marker);
                    });
                </script>
                <div id="gmap_canvas" style="height:300px;width:100%;"></div>
                <style>
                    #gmap_canvas img {
                        max-width: none!important;
                        background: none!important
                    }
                </style>
            </div>

<hr>

<!-- Post Content ... This is where you will put in data from the database-->
<p class="lead">Job Title</p>
<p><?php echo $model->title ?></p>
<p class="lead">JOB DESCRIPTION:</p>
<p class="lead">Employment Type</p>
<p><?php echo $model->employmentType ?></p>
<p class="lead">Location</p>
<p><?php echo $model->jobLocationAddress ?></p>
<p class="lead">Responsibilities</p>
<p><?php echo $model->responsibilities ?></p>
<p class="lead">Hours</p>
<p><?php echo $model->workHours ?></p>
<p class="lead">Volunteer Benefits</p>
<p><?php echo $model->incentiveCompensation ?></p>
<p class="lead">JOB REQUIREMENTS:</p>
<p class="lead">Education</p>
<p><?php echo $model->educationRequirements ?></p>
<p class="lead">Qualifications</p>
<p><?php echo $model->qualifications ?></p>
<p class="lead">Skills</p>
<p><?php echo $model->skills ?></p>
<p class="lead">Experience</p>
<p><?php echo $model->experienceRequirements ?></p>
<p class="lead">ORGANIZATION INFORMATION:</p>
<p class="lead">Hiring Organization </p>
<p><?php echo $model->hiringOrganizationName ?></p>
<p class="lead">Organization Address</p>
<p><?php echo $model->hiringOrganizationAddress ?></p>
<p class="lead">Organization Email</p>
<p><?php echo $model->hiringOrganizationEmail ?></p>
<p class="lead">Hiring Manager</p>
<p><?php echo $model->hiringOrganizationEmployeeName ?></p>

<hr>

<!-- Blog Comments -->

<!-- Comments Form -->
<div class="well">
    <h4>Leave a Comment:</h4>
    <form role="form">
        <div class="form-group">
            <textarea class="form-control" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<hr>

<!-- Posted Comments -->

<!-- Comment -->
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">Jessica Schmidt
            <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        This website is so useful! So glad I found this page!
    </div>
</div>

<!-- Comment -->
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">Simran Hayer
            <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        This website really helped me learn about potential co-op positions, Thanks!
        <!-- Nested Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Leah DeVos
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                I LOVE CO-OP! It's such a great experience to apply the knowledge we learned in class.
            </div>
        </div>
        <!-- End Comment -->
    </div>
</div>

